language: bash
os:
- linux
- osx
jobs:
  allow_failures:
    - os: osx
jdk:
- openjdk8
branches:
  only:
  - master  
install:
- mkdir ./programs ; cd ./programs ; PATH=$PATH:$PWD
- curl -fsSL https://get.nextflow.io | bash
- cd ..
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ];   then curl https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -o miniconda.sh; fi 
- bash miniconda.sh -b -p $HOME/miniconda
- source "$HOME/miniconda/etc/profile.d/conda.sh"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
script:
- set -e
- mkdir ./test_init
- cd    ./test_init
- nextflow run ../CnR-flow.nf --mode initiate
- nextflow run ../CnR-flow.nf --mode validate_all
- cd ../test_pipe/
- cat test_notes.txt
- bash setup_reference.sh
- NXF_VER="20.08.0-edge" nextflow run ./dl_prep_data.nf
- cp nextflow.config.step1 nextflow.config
- nextflow ../CnR-flow.nf --mode prep_fasta
- cp nextflow.config.step2 nextflow.config
- nextflow ../CnR-flow.nf --mode run
- cp nextflow.config.step3 nextflow.config
- nextflow ../CnR-flow.nf --mode run
