python:
- "3.6"
jdk:
- openjdk8
branches:
  only:
  - master  
install:
- curl -fsSL https://get.nextflow.io | bash
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
- bash miniconda.sh -b -p $HOME/miniconda
- source "$HOME/miniconda/etc/profile.d/conda.sh"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
script:
- ./install_cutruntools.sh
- ./nextflow run . --mode validate_all
