language: bash
os:
- linux
- osx
jdk:
- openjdk8
branches:
  only:
  - master
install:
- mkdir ./programs ; cd ./programs ; export PATH=$PATH:$PWD
- curl -fsSL https://get.nextflow.io | bash
- cd ..
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ];   then curl https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
  -o miniconda.sh; fi
- bash miniconda.sh -b -p $HOME/miniconda
- source "$HOME/miniconda/etc/profile.d/conda.sh"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then set -e ; fi
- export NXF_ANSI_LOG=false
- mkdir ./test_init
- cd    ./test_init
- nextflow run ../CnR-flow.nf --mode initiate
- cd ..

jobs:
  allow_failures:
  - os: osx
  include:
    - stage: Validate
      script:
        - cd ./test_init
        - nextflow run ../CnR-flow.nf --mode validate_all
    - stage: setup_pipe_test
      script:
        - ls
        - cd test_pipe
        - cat test_notes.txt
        - bash setup_reference.sh
        - bash dl_data.sh
        - nextflow run ./subsample_data.nf
        - cp nextflow.config.step1 nextflow.config
        - nextflow ../CnR-flow.nf --verbose --mode prep_fasta
    - stage: run_pipe_test
      name: Test_Pipe_Treat
      script:
        - ls
        - cp nextflow.config.step2 nextflow.config
        - travis_wait nextflow ../CnR-flow.nf --verbose --mode run
    - script:
        - ls
        - cp nextflow.config.step3 nextflow.config
        - travis_wait nextflow ../CnR-flow.nf --mode run
      name: Test_Pipe_Treat_Ctrl
